---
- name: Install base packages
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - base-devel
      - git
      - vim
      - tmux
      - zsh
      - curl
      - sudo
      - htop
      - ack
      - openssh
      - tig
      - unzip

- name: Install NTP
  pacman:
      name: ntp
      state: present
  when: enable_ntp | bool

- name: Enable NTP
  service:
      name: ntpd
      enabled: yes
  when: enable_ntp | bool

- name: Install sound packages
      name: "{{ item }}"
      state: present
  with_items:
      - alsa-utils
      - pulseaudio
        #- pavucontrol # only with x
  when: enable_sound | bool
